### ISSUE TITLE
add each new note to the queue

### ISSUE THREAD

**Issue by bjsi** [bjsi/incremental-writing#15]

**Comment by krisbalintona** [comment]
Perhaps you can do something like the [Spaced Repetition](https://github.com/st3v3nmw/obsidian-spaced-repetition#getting-started) plugin that uses user-defined tag(s) to indicate which notes are added the the queue.

This would be preferable to adding every note manually to the queue and having *every* note added the the queue.

**Comment by bjsi** [comment]
For the next release I just added a simple toggle to add all new notes to the default queue, I'll look into tags for the next version.
