### ISSUE TITLE
Add suggestions from @pjeby on the Obsidian Discord

### ISSUE THREAD

**Issue by bjsi** [bjsi/incremental-writing#23]
**Huge** thanks to @pjeby for these suggestions:

 FYI, there are some problems with your versioning.  manifest.json is missing the version number, and your version tags must not start with a 'v'.  Also, you have an unused private function ellipsis.  But the concept of the plugin is intriguing and I'll want to give it a try some time.

 Oh, also, you don't need to put (IW) at the end of all your command names because they'll be listed in the command palette as "Obsidian Incremental Writing Plugin: Next repetition"

 Which incidentally, there is no reason to include the words "Obsidian" or "Plugin" in the name field of your manifest, as they will be redundant when displayed in Obsidian's list of plugins.  :wink:

 So calling it just "Incremental Writing" would suffice and result in command names like "Incremental Writing: Next repetition"

 The idea of using a markdown table as a (link-preserving) database was very clever, though.  I'm curious how it handles names or text with | in, as I didn't look at how parsing or rendering are done yet.

The idea of using a markdown table as a (link-preserving) database was very clever, though.  I'm curious how it handles names or text with | in, as I didn't look at how parsing or rendering are done yet.

Be sure to put in a PR to the obsidianmd/obsidian-releases repo to get it included in the official plugin directory once you do.  I'm really looking forward to using it, and to some of your planned improvements.  Btw, do you have any plan to allow targeting sections, or just blocks and notes?

**Comment by pjeby** [comment]
One other tip: you should set your target platform to es2018, so that your generated JS will use native classes and async functions instead of emulating them.  (Eventually this will be required for all Obsidian plugins.)

**Comment by bjsi** [comment]
Thanks again for suggesting all of these fixes. I just added all of them and will make sure to make a PR to the obsidianmd/obsidian-releases repo as soon as the final issues are sorted.
