### ISSUE TITLE
Add command to add the link under the cursor to the queue

### ISSUE THREAD

**Issue by bjsi** [bjsi/incremental-writing#3]

**Comment by pjeby** [comment]
Just as an FYI: you can hook the `file-menu` event to add a menu item to the context menu for links...  and it will then show up in the title menu for notes, the file explorer, backlinks pane, etc.  (Pretty much any place Obsidian displays files.)  While that's not the same as a *command*, it should still be quite useful.  :wink:

**Comment by bjsi** [comment]
@pjeby ahhhhhhh thanks so much that's really useful info

**Comment by bjsi** [comment]
added!
