### ISSUE TITLE
Silent error if queue folder exists

### ISSUE THREAD

**Issue by pjeby** [bjsi/incremental-writing#32]
Upon installing the plugin, I configured it to use a queue file of "To Review" under my "Inbox" folder, then tried to open the queue file.  Nothing happened, so I checked the console and saw "Error: Folder already exists".  Apparently the default queue creation unconditionally tries to create a folder, rather than verifying whether the folder exists first.

(It's also not clear to me why there are separate settings for the file and folder names in the first place, vs. using a single note specifier field (with suggestions) as is done by the Zettelkasten prefixer, daily notes, and other plugins' settings for template files.)

**Comment by pjeby** [comment]
Related issue: the setting for the filename doesn't work correctly if it doesn't have an .md extension.  However, since the .md extension is required, the setting shouldn't need to include it.  (Again, see other plugins' settings that reference a specific note: they use the path+base name only.)

**Comment by bjsi** [comment]
Good points, I really botched the file / folder handling in 0.2. I took a look at some other plugins and I think I've solved all of these issues. Also liam showed me some code to implement the dropdown suggestions like the the Zettelkasten prefixer and daily notes plugins. I'll leave this open until I after I get the next version out just in case.
