### ISSUE TITLE
Trouble using bulk add options

### ISSUE THREAD

**Issue by paulbricman** [bjsi/incremental-writing#40]
> You can also add the output from an inbuilt search to a queue. Do a search and click the button at the top of the search pane to try it out. You can also right click on folders, files and links to add them to queues through the context menu.

I'm having trouble using any of these methods of adding notes in bulk to the queue. I can't really find the new button at the top of the search pane. And right clicking on files/folders doesn't show anything related to the plugin? Adding everything to the initial queue would really make it easy to get going with IW!

**Comment by paulbricman** [comment]
Maybe it's because the commit which describes bulk adding was made after the last release? dcd57a3875a2d35702299479c0499221a3742c30

**Comment by bjsi** [comment]
Oh damn is it not a part of release 0.2? Then I screwed something up haha. Okay I will get things sorted and release this through Obsidian's proper plugin system.
