### ISSUE TITLE
Remove deleted notes from the queue

### ISSUE THREAD

**Issue by selfire1** [bjsi/incremental-writing#46]
Hi! This plugin is amazing, thank you a lot for the effort you put in.

Would it be possible to automatically remove deleted notes from the queue? Otherwise the plugin creates empty notes with the header once they come up in the queue.

**Comment by bjsi** [comment]
Yeah that shouldn't be too difficult to add in. I'll add that into the next version.

**Comment by selfire1** [comment]
Sweet, thank you!
