### ISSUE TITLE
Smart add new notes to queue

### ISSUE THREAD

**Issue by bjsi** [bjsi/incremental-writing#49]
Perhaps you can do something like the [Spaced Repetition](https://github.com/st3v3nmw/obsidian-spaced-repetition#getting-started) plugin that uses user-defined tag(s) to indicate which notes are added the the queue.

This would be preferable to adding every note manually to the queue and having *every* note added the the queue.

_Originally posted by @krisbalintona in https://github.com/bjsi/incremental-writing/issues/15#issuecomment-824340510_

**Comment by phillipjohnston** [comment]
This would be really helpful, especially for managing multiple queues

**Comment by bathrobe** [comment]
This would be such a huge help. Using this plugin + MarkDownload for incremental reading is so much fun, but annoying without "Add new notes to queue". Then daily notes, etc. end up being reviewed, which is non-ideal.

**Comment by bjsi** [comment]
Sorry for taking ages to get back to you. I have pretty much finished implementing this feature. It basically works like this: 

If you have notes with a bunch of tags already added that you want to add to a queue, you can search for tag:#\<tag name\> in the search pane and add them all with the Add to IW Queue button. This makes it easy to add the backlog of tagged notes you've already made.

Then you can go to your settings and create a mapping between queue names and a comma separated list of tags. The format for each will be: \<queue name\>=\<comma separated list of tags\>

It will look something like this:

IW-Queue=iw-queue,writing
Tasks=tasks,todos

So now each time you add a tag that is mapped to an incremental writing queue to a note, that note will automatically get added to the corresponding queue for you.

Let me know if that sounds ok. I will test it for a week or so longer to make sure there are no issues before releasing.

**Comment by phillipjohnston** [comment]
Sounds great to me - looking forward to trying it out. Thank you!

**Comment by bathrobe** [comment]
Yeah that sounds fantastic. Big fan of this plugin and all the work you do!
