### ISSUE TITLE
Feature Request: inbox processing

### ISSUE THREAD

**Issue by derekvan** [bjsi/incremental-writing#50]
I really like the concept of inbox processing from Andy Matuschak and it seems like this plugin could support it with a few tweaks. Would it be possible to add options when marking a repetition complete to adjust the interval time like shown in this video: https://www.youtube.com/watch?v=zG5r7QIY_TM (where you can set it to normal repetition time, sooner, or later)

**Comment by bjsi** [comment]
Sure thing, this should be fairly easy to implement, and has been requested by a couple of people on Discord too.
