### ISSUE TITLE
Adding links within note to the IW Queue does nothing

### ISSUE THREAD

**Issue by phillipjohnston** [bjsi/incremental-writing#52]
I'm working on a project and have an index note with a hundred links or so to other notes. I tried adding all links within the note to the queue using the command palette, but it appears to have done nothing. Have you run into this before, or do you think I am missing a step?

**Comment by bjsi** [comment]
I have done quite a bit of refactoring to the code related to bulk adding notes and links to queues recently and it seems to be working for me. It will get released into the next version soon so hopefully that should fix things for you. I will keep this issue open until a couple weeks after the next release so if there are any issues you can let me know.

**Comment by phillipjohnston** [comment]
Sounds good @bjsi, when I see the new version drop I'll do some testing and confirm.

**Comment by bjsi** [comment]
New version available now, let me know how it goes.

**Comment by phillipjohnston** [comment]
Worked great - I now see the popup, and all the links are added to the desired queue. Closing as resolved.
