### ISSUE TITLE
note auto queued from tag are getting incorrect next rep date

### ISSUE THREAD

**Issue by um1642** [bjsi/incremental-writing#57]
Hi, 
I'am currently evaluating the plugin to see if it could fit my workflow and it seems very promizing... nice job.

When an note is automatically queued due to being tagged with a mapped tag. The "Next Rep" is 1970-01-01 instead of the configured "Default first rep date".
to reproduce:
- configure a queue tag
- configure a different "Default first rep date" like "tomorrow" instead of the default "1970-01-01"
- create a note and  tag it with the configured tag
- check the "next rep" for the note in the queue file and it will still be "1970-01-01"

**Comment by bjsi** [comment]
Thanks for letting me know, just fixed it now. Will be in the next release in a few days.
