### ISSUE TITLE
Hope - To support load Queue-Files from Sub-Dir of the Root-Dir

### ISSUE THREAD

**Issue by wslldsdhii** [bjsi/incremental-writing#60]
I hope you could add new feature of to be able to load Queue-File from subdirectories

**Comment by bjsi** [comment]
I realized that there were some bugs with loaded queues from sub directories. I think I fixed them all in a recent commit. The fixes will be available in a new version update in a few days.

**Comment by bjsi** [comment]
Ok the fix is available now in version 4.1. Let me know if there are still issues.
