### ISSUE TITLE
Remove Current Note Command

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [bjsi/incremental-writing#67]
If I'm cycling through a queue and I hit a note I don't want to see in that queue again, I'd like to be able to run a command to remove it from the current queue

**Comment by geoffreysflaminglasersword** [comment]
I'll be happy to implement this if I get the time

**Comment by base-I** [comment]
Isn't the "dismiss current repetition" doing just that?

**Comment by geoffreysflaminglasersword** [comment]
> Isn't the "dismiss current repetition" doing just that?

Oh, you know what it is. I thought 'dismissing' was just ignoring it and sending it around again
